name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows environments

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: |
          npm install
          ls -l node_modules/.bin  # Check permissions and existence of Jest
          npm list jest            # Check if Jest is installed
          npm test                 # Run Jest tests
